mkgif_project/mkgif/urls.py
from django.urls import path
from . import views


app_name = 'mkgif'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:pk>/', views.details, name='details'),
]

mkgif_project/mkgif_project/urls.py
# from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mkgif.urls'))
]

# if settings.DEBUG:
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkgif_project/mkgif/models.py
from django.db import models


class Animation(models.Model):
    name = models.CharField(max_length=200)


class Image(models.Model):
    def image_path(self, filename):
        return f'{self.animation.pk}/{filename}'

    animation = models.ForeignKey('Animation', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_path)

mkgif_project/mkgif/views.py
from django.shortcuts import get_object_or_404, render
from .models import Animation, Image


def index(request):
    if request.method == 'POST':
        anim = Animation.objects.create(name=request.POST['name'])
        for img in request.FILES.getlist('imgs'):
            Image.objects.create(animation=anim, image=img)

    anims = Animation.objects.all()
    context = {
        'anims': anims
    }
    return render(request, 'mkgif/index.html', context)


def details(request, pk):
    anim = get_object_or_404(Animation, pk=pk)
    images = Image.objects.filter(animation=pk)
    context = {
        'anim': anim,
        'images': images
    }
    return render(request, 'mkgif/details.html', context)

mkgif_project/mkgif/templates/mkgif/details.html
{% extends "index.html"}

{% block main %}
<h3>Details of animation</h3>

<img src="{{ MEDIA_URL }}/{{ Image.image_path }}">

{% endblock main %}

mkgif_project/mkgif/templates/mkgif/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make GIF</title>
</head>

<body>
    <header>
        <h1>Make GIF Animations</h1>
    </header>
    <main>
        <p>My GIF Animations:</p>
        <table>
            {% for anim in anims %}
            <tr>
                <td>{{ anim.pk }}</td>
                <td><a href="{% url 'mkgif:details' anim.pk %}">{{ anim.name }}</a></td>
            </tr>
            {% endfor %}
        </table>
        <hr>
        <form action="{% url 'mkgif:index' %}" method="POST" enctype="multipart/form-data">
            <fieldset>
                <legend><label>Add New GIF Animation</label></legend>
                {% csrf_token %}
                <input name="name" type="text" placeholder="Animation name">
                <input name="imgs" type="file" multiple>
                <button>Submit</button>
            </fieldset>
        </form>
    </main>
</body>

</html>